<% require 'kitchen-sync' %>
---

driver:
  name: docker
  privileged: true
  publish_all: true
  use_sudo: false
  require_chef_omnibus: false
  dns:
    - 8.8.8.8
    - 8.8.4.4

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer
  cookbooks_path:
    - ../cookbooks

platforms:
  - name: centos-7.2
    driver_config:
      image: centos:7
      platform: rhel
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - /bin/yum install -y initscripts net-tools wget
        - curl -L https://www.opscode.com/chef/install.sh | bash


suites:
  - name: nginx
    driver_config:
      instance_name: nginx
      forward:
        - 8090:80
    run_list:
      - recipe[nginx::default]
    attributes:
      nginx:
        app_name: apache_web
        service_list:
          - 172.28.169.88:8091
          - 172.28.169.88:8092
          - 172.28.169.88:8093
          - 172.28.169.88:8094
